language: php
php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.6.*

before_script:
    - phpenv config-add myconfig.ini
    - composer self-update
    - composer install

    - app/console doctrine:database:create
    - app/console cache:clear --env=prod
    - app/console cache:clear --env=dev
script:
  - phpunit -c app/